### ISSUE TITLE
Train script.

### ISSUE THREAD

**Issue by mememimis** [jamiechoi1995/ACCESS#1]
Very interesting  work. Is it possible  to upload the training  script as well?

**Comment by jamiechoi1995** [comment]
https://github.com/jamiechoi1995/PanoSegAtt/commit/bf41b50f0bbbd200cdcb348298fcc10f62f0e861bf41b50

**Comment by mikkkeldp** [comment]
You need the data folder to train and anyone outside of China can't run this repo since baidu is only accessible from within China.
