### ISSUE TITLE
Regarding model downloading

### ISSUE THREAD

**Issue by rahuldev5** [jamiechoi1995/ACCESS#2]
Hi Jamie, people outside china cannot download models from pan Baidu. Can you please provide some other way to download them? Thank You.

**Comment by jamiechoi1995** [comment]
Due to the GFW, it seems that it is the only way to upload big files on Pan Baidu. You can try to generate the feature by yourself.

**Comment by rahuldev5** [comment]
Can you please just guide me through the process once?
Thanks & Regards.
